@startuml Renderer

' Events:
' - New Data
' - Resize
' - Zoom
' - Panned
' - Done Rendering

state Unitialized
state Idle
state Rendering

[*] -> Unitialized

Unitialized -d-> Rendering : New Data / Invalidate Everything

Rendering -> Rendering : New Data, Zoom\n/ Cancel Render,\nInvalidate Everything
Rendering -> Rendering : Resize\n/ Cancel Render,\nResize Instructions
Rendering -> Rendering : Panned\n/ Cancel Render,\nPan Instructions
Rendering -l-> Idle : Done Rendering

Idle -> Rendering : New Data, Zoom\n/ Invalidate Everything
Idle -> Rendering : Resize\n/ Resize Instructions
Idle -> Rendering : Panned\n/ Pan Instructions

@enduml