@startuml Renderer

' Events:
' - New Data
' - Resize
' - Zoom
' - Start Pan
' - End Pan
' - Done Rendering

state Unitialized
state Idle
state Panning
state Rendering {
    state Normal : entry / Start Render
    state Paused : entry / Cancel Render
    state Paused : Params Changed / NOTHING
    [*] -> Normal
    Normal -> Paused : Start Pan
    Paused -> Normal : End Pan
}

[*] -> Unitialized

Unitialized -d-> Rendering : New Data / Invalidate Everything

Rendering -> Rendering : New Data, Zoom\n/ Cancel Render,\nInvalidate Everything
Rendering -> Rendering : Resize\n/ Cancel Render,\nInstructions for new size
Rendering -l-> Idle : Done Rendering

Idle -d-> Panning : Start Pan
Idle -> Rendering : New Data, Zoom\n/ Invalidate Everything
Idle -> Rendering : Resize\n/ Instructions for new size

Panning -u-> Rendering : End Pan / Update Instructions From Pan



@enduml