# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: macOS Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Buddhabrot.sln
    - name: Build
      run: dotnet build --no-restore -c Release src/Buddhabrot.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release src/Buddhabrot.sln